[profile.default]
src = "packages/contracts/src"
out = "packages/contracts/out"
test = "packages/contracts/test"
script = "packages/contracts/script"
libs = ["lib", "node_modules"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "poseidon2-evm/=node_modules/poseidon2-evm/",
]
