[workspace]
members = [
    "members/aggregator",
    "members/ecdsa_spendability",
    "members/dummy/spendability",
    "members/dummy/inclusion",
    "members/poseidon2_inclusion",
    "members/test",
    "members/chonk_kernel",
]
