// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {N_PUB} from "../lib/Constants.sol";

// Interface matching the verifier contract generated by snarkjs for the Aggregator circuit
interface IVerifier {
    function verify(uint256[8] calldata proof, uint256[N_PUB] calldata pubSignals) external view;
}
