// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {N_PUB} from "../lib/Constants.sol";

// Interface matching the verifier contract generated by snarkjs for the Aggregator circuit
interface IVerifier {
    function verifyProof(
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC,
        uint[N_PUB] calldata pubSignals
    ) external view returns (bool);
}
