// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Interface matching the verifier contract generated by snarkjs for the Aggregator circuit
// (6 inputs, 6 outputs → 44 public signals).
interface IVerifier {
    function verifyProof(
        uint[2] memory pA,
        uint[2][2] memory pB,
        uint[2] memory pC,
        uint[44] memory pubSignals
    ) external view returns (bool);
}
