//! FFI bindings into Go/gnark's multisig-spendability circuit library.

use ark_bn254::Fr;
use k256::ecdsa::{Signature, VerifyingKey};
use tint::{
    circuit::join_split::{N_INPUTS, N_OUTPUTS, N_WITHDRAWALS},
    note::{commitment::Commitment, withdrawal::Withdrawal},
    operation::Operation,
};

use crate::N_SIGNERS;

pub mod artifacts;
mod bytes32;
mod operation_hash_test;
mod poseidon2_test;
mod pubkey_hash_test;

/// Generated by build.rs from go via bindgen. See `go/ffi/tint.h` for
/// documentation of the C types and functions.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
use bindings::{
    Bytes32, FreeBytes, TintBaseCommitment, TintOperation, TintProve, TintProveInput, TintPubKeyXY,
    TintSignatureRS, TintSpendableCommitment, TintWithdrawal,
};

#[derive(Clone, Debug, thiserror::Error)]
pub enum FfiError {
    #[error("Prove failed with status code {0}")]
    ProveFailed(u8),
    #[error(transparent)]
    InvalidPublicKey(#[from] crate::pubkey_hash::InvalidPublicKey),
}

/// Generates a proof for the multisig-spendability circuit using gnark
/// for the given inputs.
///
/// Returns the proof as solidity-verifier-compatible bytes on success or
/// the status code on failure.
pub fn prove_via_go(
    ccs: &[u8],
    pk: &[u8],
    vk: &[u8],
    spendability_address: Fr,
    operation: &Operation<N_INPUTS, N_OUTPUTS, N_WITHDRAWALS>,
    pub_keys: &[VerifyingKey; N_SIGNERS],
    signatures: &[Option<Signature>; N_SIGNERS],
) -> Result<Vec<u8>, FfiError> {
    let mut input = TintProveInput {
        spendability_address: spendability_address.into(),
        operation: operation.into(),
        pub_keys: tint::array::try_from_fn(|i| TintPubKeyXY::try_from(&pub_keys[i]))?,
        signatures: std::array::from_fn(|i| signatures[i].as_ref().into()),
    };

    let mut proof_ptr: *mut u8 = std::ptr::null_mut();
    let mut proof_len: usize = 0;

    let status = unsafe {
        TintProve(
            ccs.as_ptr().cast_mut(),
            ccs.len(),
            pk.as_ptr().cast_mut(),
            pk.len(),
            vk.as_ptr().cast_mut(),
            vk.len(),
            &mut input,
            &mut proof_ptr,
            &mut proof_len,
        )
    };

    if status != 0 {
        return Err(FfiError::ProveFailed(status));
    }

    let proof = unsafe { std::slice::from_raw_parts(proof_ptr, proof_len) }.to_vec();
    unsafe { FreeBytes(proof_ptr) };
    Ok(proof)
}

impl From<&Operation<N_INPUTS, N_OUTPUTS, N_WITHDRAWALS>> for TintOperation {
    fn from(op: &Operation<N_INPUTS, N_OUTPUTS, N_WITHDRAWALS>) -> Self {
        let inputs = std::array::from_fn(|i| TintSpendableCommitment {
            inner: (&op.inputs[i]).into(),
            spendability_address: op.inputs[i].spendability_address_fr().into(),
            spendability_witness: op.inputs[i].spendability_witness_fr().into(),
        });
        let output_commitments = std::array::from_fn(|i| (&op.output_commitments[i]).into());
        let output_withdrawals = std::array::from_fn(|i| (&op.output_withdrawals[i]).into());

        TintOperation {
            inputs,
            output_commitments,
            output_withdrawals,
        }
    }
}

impl<C: Commitment> From<&C> for TintBaseCommitment {
    fn from(c: &C) -> Self {
        TintBaseCommitment {
            asset_fr: c.asset_fr().into(),
            amount_fr: c.amount_fr().into(),
            spendability_hash: c.spendability_hash().into(),
            random_fr: c.random_fr().into(),
            nullifier_pub_key: c.nullifier_pub_key().0.into(),
        }
    }
}

impl From<&Withdrawal> for TintWithdrawal {
    fn from(w: &Withdrawal) -> Self {
        TintWithdrawal {
            asset_fr: w.asset_fr().into(),
            amount_fr: w.amount_fr().into(),
        }
    }
}

impl TryFrom<&VerifyingKey> for TintPubKeyXY {
    type Error = crate::pubkey_hash::InvalidPublicKey;

    fn try_from(vk: &VerifyingKey) -> Result<Self, Self::Error> {
        let (x, y) = crate::pubkey_hash::encoded_xy(vk)?;
        Ok(TintPubKeyXY {
            x: Bytes32 { data: x },
            y: Bytes32 { data: y },
        })
    }
}

/// A missing signature is encoded as `r = s = 0`, which the circuit's
/// ECDSA-verify gadget treats as automatically invalid.
impl From<Option<&Signature>> for TintSignatureRS {
    fn from(sig: Option<&Signature>) -> Self {
        let Some(sig) = sig else {
            return TintSignatureRS {
                r: Bytes32 { data: [0u8; 32] },
                s: Bytes32 { data: [0u8; 32] },
            };
        };
        let (r, s) = sig.split_bytes();
        TintSignatureRS {
            r: Bytes32 { data: r.into() },
            s: Bytes32 { data: s.into() },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::THRESHOLD;

    #[test]
    fn consts_match() {
        assert_eq!(bindings::N_INPUTS, N_INPUTS as u32);
        assert_eq!(bindings::N_OUTPUTS, N_OUTPUTS as u32);
        assert_eq!(bindings::N_WITHDRAWALS, N_WITHDRAWALS as u32);
        assert_eq!(bindings::N_SIGNERS, N_SIGNERS as u32);
        assert_eq!(bindings::THRESHOLD, THRESHOLD as u32)
    }
}
