// auto-generated by circomkit
pragma circom 2.1.2;

include "../aggregator.circom";

component main {public[oldRoot, newRoot, leavesAggregationHash, nullifiers, commitmentsOut, unshieldAmounts, unshieldAssets, dataHash]} = Aggregator(5, 5, 3, 15);
