// auto-generated by circomkit
pragma circom 2.1.2;

include "../aggregator.circom";

component main {public[oldRoot, newRoot, startAggregationHash, endAggregationHash, nullifiers, spendabilityHashesIn, commitmentsOut, unshieldAmounts, unshieldAssets, boundParamsHash]} = Aggregator(5, 5, 5, 22);
