// auto-generated by circomkit
pragma circom 2.1.2;

include "../aggregator.circom";

component main {public[stagingRoot, archiveRoot, nullifiers, commitmentsOut, unshieldRecipients, unshieldAmounts, unshieldAssets, spendabilityAddressesIn, spendabilityDataIn]} = Aggregator(4, 4, 8, 40);
